export const stocks = [
  {
    id: 1,
    symbol: "RELIANCE",
    name: "Reliance Industries",
    longName: "Reliance Industries Limited",
  },
  {
    id: 2,
    symbol: "BHARTIARTL",
    name: "Bharti Airtel",
    longName: "Bharti Airtel Limited",
  },
  {
    id: 3,
    symbol: "HDFCBANK",
    name: "HDFC Bank",
    longName: "HDFC Bank Limited",
  },
  {
    id: 4,
    symbol: "ICICIBANK",
    name: "ICICI Bank",
    longName: "ICICI Bank Limited",
  },
  {
    id: 5,
    symbol: "SBIN",
    name: "State Bank of India",
    longName: "State Bank of India",
  },
  {
    id: 6,
    symbol: "TCS",
    name: "Tata Consultancy Services",
    longName: "Tata Consultancy Services Limited",
  },
  {
    id: 7,
    symbol: "BAJFINANCE",
    name: "Bajaj Finance",
    longName: "Bajaj Finance Limited",
  },
  {
    id: 8,
    symbol: "LT",
    name: "Larsen & Toubro",
    longName: "Larsen & Toubro Limited",
  },
  {
    id: 9,
    symbol: "HINDUNILVR",
    name: "Hindustan Unilever",
    longName: "Hindustan Unilever Limited",
  },
  {
    id: 10,
    symbol: "SUNPHARMA",
    name: "Sun Pharma",
    longName: "Sun Pharmaceutical Industries Limited",
  },
  {
    id: 11,
    symbol: "INFY",
    name: "Infosys",
    longName: "Infosys Limited",
  },
  {
    id: 12,
    symbol: "MARUTI",
    name: "Maruti Suzuki",
    longName: "Maruti Suzuki India Limited",
  },
  {
    id: 13,
    symbol: "TITAN",
    name: "Titan Company",
    longName: "Titan Company Limited",
  },
  {
    id: 14,
    symbol: "ADANIPORTS",
    name: "Adani Ports",
    longName: "Adani Ports and Special Economic Zone Limited",
  },
  {
    id: 15,
    symbol: "KOTAKBANK",
    name: "Kotak Mahindra Bank",
    longName: "Kotak Mahindra Bank Limited",
  },
  {
    id: 16,
    symbol: "M&M",
    name: "Mahindra & Mahindra",
    longName: "Mahindra & Mahindra Limited",
  },
  {
    id: 17,
    symbol: "AXISBANK",
    name: "Axis Bank",
    longName: "Axis Bank Limited",
  },
  {
    id: 18,
    symbol: "HCLTECH",
    name: "HCL Technologies",
    longName: "HCL Technologies Limited",
  },
  {
    id: 19,
    symbol: "ITC",
    name: "ITC",
    longName: "ITC Limited",
  },
  {
    id: 20,
    symbol: "ULTRACEMCO",
    name: "UltraTech Cement",
    longName: "UltraTech Cement Limited",
  },
];
